# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TbasWJbwP_-PFYOHBhXmXZW_qO7SPfEA
"""

import random
arr = []
for i in range(1,16):
  arr.append(random.randint(1,20))
arr

import numpy as np
arr1 = np.array(arr)
arr1

arr2 = arr1.reshape(3,5)
arr2

print(arr2.shape)

maxNum = np.amax(arr2, axis=1) 
arr2 = np.where(np.isin(arr2,maxNum), 0, arr2)
print(arr2)

import pandas as pd
df = pd.read_csv("data.csv")

pd.read_csv("https://drive.google.com/drive/folders/1h8C3mLsso-R-sIOLsvoYwPLzy2fJ4IOF?usp=sharing")

df.describe()

df.isnull()

print(df.isnull())

df = df.fillna(df.mean())

df.isna().any()

df.agg(["min","max","count","mean"])

df[(df["Calories"] >  500) & (df["Calories"]<1000)]

df[(df["Calories"] >  500) & (df["Pulse"]<100)]

df_modified = df[["Duration", "Pulse","Calories"]]

df_modified

df.drop(columns=["Maxpulse"])

df.dtypes

df['Calories'] = df["Calories"].astype(int)

df.plot.scatter(x="Duration", y="Calories")

import matplotlib.pyplot as plt
# Data to plot
languages = 'Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++'
popuratity = [22.2, 17.6, 8.8, 8, 7.7, 6.7]
colors = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b"]
explode = (0.1, 0.1, 0.05, 0,0.07,0)  
plt.pie(popuratity, explode=explode, labels=languages, colors=colors, autopct='%1.1f%%', shadow=True, startangle=140)
plt.axis('equal')
plt.show()

